# Generated by Django 3.0.7 on 2020-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_commune', '0003_submission_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_sent',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Date Posted'),
        ),
    ]
