# Generated by Django 3.1 on 2020-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_commune', '0004_submission_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='flagged',
            field=models.BooleanField(default=False, editable=False, verbose_name='Flagged'),
        ),
    ]
