# Generated by Django 3.1 on 2020-10-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_commune', '0005_submission_flagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': [('flag', 'Can flag submissions'), ('unflag', 'Can unflag submissions')], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
    ]
