# Generated by Django 3.1 on 2021-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_commune', '0006_auto_20201002_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(verbose_name='Words')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Filter Word',
                'verbose_name_plural': 'Filter Words',
            },
        ),
    ]
